import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { defaultVoice, listVoices, resolveVoice, voiceDirectories } from '../broker/tts.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
function option(name: string, fallback: string) {
  const i = args.indexOf(name); return i < 0 ? fallback : resolve(args[i + 1] || (() => { throw new Error(`Missing ${name} value`); })());
}
if (args.some((arg, i) => i % 2 === 0 && !['--config-dir', '--voices-dir'].includes(arg))) throw new Error('Usage: setup-speech.ts [--config-dir DIR] [--voices-dir DIR]');
const configDir = option('--config-dir', join(process.env.XDG_CONFIG_HOME || join(homedir(), '.config'), 'speech-dispatcher'));
const voicesDir = option('--voices-dir', process.env.CERE_VOICES_DIR || join(process.env.XDG_DATA_HOME || join(homedir(), '.local/share'), 'piper/voices'));
const overrideVoices = args.includes('--voices-dir') || !!process.env.CERE_VOICES_DIR;
await mkdir(voicesDir, { recursive: true });
const amy = await resolveVoice(defaultVoice, [join(root, 'tts/voices'), join(root, 'build/tts/voices')]);
async function copy(source: string, target: string) {
  try { await copyFile(source, target, constants.COPYFILE_EXCL); } catch (error: any) { if (error.code !== 'EEXIST') throw error; }
}
await copy(amy.model, join(voicesDir, defaultVoice + '.onnx'));
await copy(amy.config, join(voicesDir, defaultVoice + '.onnx.json'));
const bundle = dirname(dirname(amy.model));
for (const [source, target] of [['voices/MODEL_CARD', defaultVoice + '.MODEL_CARD'], ['NOTICES.md', defaultVoice + '.NOTICES.md'], ['licenses/MIMIC3-CC-BY-SA-4.0.txt', 'MIMIC3-CC-BY-SA-4.0.txt']] as const) await copy(join(bundle, source), join(voicesDir, target));
const voices = await listVoices(overrideVoices ? [voicesDir] : voiceDirectories());
if (!voices.some(v => v.id === defaultVoice)) throw new Error('Amy voice pair is incomplete');
const shellQuote = (text: string) => "'" + text.replaceAll("'", "'\\''") + "'";
const confQuote = (text: string) => '"' + text.replaceAll('\\', '\\\\').replaceAll('"', '\\"') + '"';
const command = `printf %s '$DATA' | ${overrideVoices ? `CERE_VOICES_DIR=${shellQuote(voicesDir)} ` : ''}${shellQuote(process.execPath)} ${shellQuote(join(root, 'broker/tts-synth.ts'))} '$VOICE'`;
const module = [
  '# Generated by Cere; rerun setup-speech.ts after adding custom voices.',
  'Debug 0', `GenericExecuteSynth ${confQuote(command)}`, 'GenericCmdDependency "aplay"',
  'GenericMaxChunkLength 10000', 'GenericDelimiters "|"', 'GenericDefaultCharset "utf-8"',
  `DefaultVoice "${defaultVoice}"`,
  ...voices.map(v => `AddVoice "${v.language.replaceAll('_', '-').toLowerCase()}" "FEMALE1" "${v.id}"`), '',
].join('\n');
await mkdir(join(configDir, 'modules'), { recursive: true });
const moduleFile = join(configDir, 'modules/cere-piper.conf');
// This named module belongs to Cere. Existing dispatcher modules/defaults stay intact.
await writeFile(moduleFile, module);
const main = join(configDir, 'speechd.conf');
let current: string;
try { current = await readFile(main, 'utf8'); }
catch (error: any) { if (error.code !== 'ENOENT') throw error; current = 'AudioOutputMethod "pulse"\nDefaultModule "cere-piper"\n'; }
const registration = 'AddModule "cere-piper" "sd_generic" "cere-piper.conf"';
if (!/^\s*AddModule\s+"cere-piper"\s/m.test(current)) {
  if (/^\s*BeginClient\b/m.test(current)) current = registration + '\n' + current;
  else current += '\n' + registration + '\n';
  await writeFile(main, current);
}
console.log(`Installed ${defaultVoice} in ${voicesDir}\nRegistered ${voices.length} voice(s) in ${moduleFile}\nRestart your user speech-dispatcher service, then use /tts-test in Cere. Existing default modules are preserved.`);
